CREATE TABLE [dbo].[TaskKSBs](
    [TaskId] [int] NOT NULL,
    [KSBProgressId] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TaskKSBs] ADD  CONSTRAINT [PK_TaskKSBs] PRIMARY KEY CLUSTERED 
(
    [TaskId] ASC,
    [KSBProgressId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
